### ISSUE TITLE
Bug: Fehler wenn in der config.xml kein Wert bei <File></File> angegeben ist

### ISSUE THREAD

**Issue by mcmicha** [H-J-P/Ikarus#4]
Wenn in der config.xml Datei kein Wert für <File> angegeben ist, dann gibt es den folgenden Fehler.

`12:36:07.055  (C) H.J.P. 2016  Version 0.9916   Application started .. 
12:36:07.122  Read file to dataset: Config.xml
12:36:07.135  Config.xml problem .. System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Ikarus.MainWindow..ctor() in C:\Users\Heinz\Dropbox\Projects\Ikarus\Ikarus\Ikarus\MainWindow.xaml.cs:line 173
12:36:07.135  ++++++ File not found: C:\Users\dragon\Desktop\Ikarus\Ikarus\
12:36:07.135  XmlToDataSet problem .. System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Ikarus.MainWindow..ctor() in C:\Users\Heinz\Dropbox\Projects\Ikarus\Ikarus\Ikarus\MainWindow.xaml.cs:line 189
12:36:07.232  Reset Cockpit .. 
12:36:07.280  DatasetToXml: C:\Users\dragon\Desktop\Ikarus\Ikarus\ ... System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\dragon\Desktop\Ikarus\Ikarus\'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.Data.DataSet.WriteXml(String fileName, XmlWriteMode mode)
   at Ikarus.ImportExport.DatasetToXml(String fileName, DataSet ds) in C:\Users\Heinz\Dropbox\Projects\Ikarus\Ikarus\Ikarus\ImportExport.cs:line 68
12:36:07.280  Save file: 
12:36:07.402  Listener started on Port 1625...
12:36:34.496  Reset Cockpit .. 
12:36:34.510  Start loading Cockpit ... 
12:36:34.529  End loading Cockpit ... 
`

**Comment by H-J-P** [comment]
Das ist richtig. Hast Du die Config.xml manuell verändert?

**Comment by H-J-P** [comment]
15:56:29.185  (C) H.J.P. 2016  Version 0.9916   Application started .. 
15:56:29.216  Read file to dataset: Config.xml
15:56:29.216  ++++++ None definitions for lamps found.
15:56:29.216  ++++++ None definitions for switches found.
15:56:29.231  Reset Cockpit .. 
15:56:29.278  Listener started on Port 1625...

Ist erledigt!

**Comment by H-J-P** [comment]
16:11:06.715  (C) H.J.P. 2016  Version 0.9916   Application started .. 
16:11:06.774  Read file to dataset: Config.xml
**16:11:06.775  ++++++ None configuration loaded. File=''**
16:11:06.775  ++++++ None definitions for lamps found.
16:11:06.775  ++++++ None definitions for switches found.
16:11:06.840  Reset Cockpit .. 
16:11:06.968  Listener started on Port 1625...

**Comment by mcmicha** [comment]
Ja, habe ich.
Ich will gerade die Doku schreiben und habe mir ein paar Screenshots gemacht und wollte ein komplettleeren haben, wie das bei einer ersteinrcihtung sein könnte.
Daher kommt das....

**Comment by H-J-P** [comment]
Du schreibst eine Doku? Bitte dann sehr kurz und knackig. Die vorhandenen Profile zeigen eigentlich alles und sind für sich die beste Dokumentation der Anwendung. Für mich waren Beispiele immer wichtiger.
