### ISSUE TITLE
Udp Timertick

### ISSUE THREAD

**Issue by boldestfortune** [H-J-P/Ikarus#7]
So the screen froze up, checked the ikarus log with this error:

20:26:18.465  UdpTimerTick ... System.NullReferenceException: Object reference not set to an instance of an object.
   at Ikarus.MainWindow.GrabValues() in Z:\Documents\Ikarus_Source\Ikarus_Source\Ikarus\Ikarus\MainWindow.xaml.cs:line 882
   at Ikarus.MainWindow.UdpTimerTick(Object sender, EventArgs e) in Z:\Documents\Ikarus_Source\Ikarus_Source\Ikarus\Ikarus\MainWindow.xaml.cs:line 349
20:27:27.561  Cockpit closed .. 
20:27:28.016  Reset Cockpit .. 

upon reopening it did not re acquire the connection. Any way to correct?

Great program btw!

**Comment by H-J-P** [comment]
I have not seen this bug yet. Which version did you use?

**Comment by boldestfortune** [comment]
Version of DCS or Ikarus?
